name: Compilar Kernel Legion 2 Pro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Instalar Herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison lld llvm libssl-dev libelf-dev python3 python2-minimal
          sudo ln -sf /usr/bin/python3 /usr/bin/python

      - name: Configurar y Compilar
        run: |
          export ARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          
          # Generar configuración base del Legion 2
          make vendor/lahaina-gki_defconfig
          
          # Forzar activación de KernelSU-Next
          echo "CONFIG_KSU=y" >> arch/arm64/configs/vendor/lahaina-gki_defconfig
          
          # Compilar (ignorar errores visuales con KCFLAGS)
          make -j$(nproc) KCFLAGS="-Wno-error" || make -j$(nproc)

      - name: Subir Kernel Listo
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Legion2-Pro
          path: arch/arm64/boot/Image.gz
